### ISSUE TITLE
Problem asound.conf

### ISSUE THREAD

**Issue by betojsp** [maximtrp/spectrumLED#1]
Hi, I have tried to configure the asound.conf and it does not work.
Hardware
(0, 'bcm2835 ALSA: - (hw:0,0)', 0)
(1, 'bcm2835 ALSA: IEC958/HDMI (hw:0,1)', 0)
(2, 'USB Audio DAC: - (hw:1,0)', 0)
(3, 'Loopback: PCM (hw:2,0)', 32)
(4, 'Loopback: PCM (hw:2,1)', 32)
(5, 'sysdefault', 0)
(6, 'default', 0)
(7, 'dmix', 0)

I make the changes in the example asound.conf and I do not have audio.

You can help me.

Thanks

**Comment by maximtrp** [comment]
Please post your `asound.conf` contents.

**Comment by betojsp** [comment]
pcm.!default {
	type plug
	playback.pcm "out"
	capture.pcm "loopin"
}
pcm.out {
    type plug
    slave.pcm {
        type multi
        slaves {
            a { channels 2 pcm "output" }
            b { channels 2 pcm "loopout" }
        }
        bindings {
            0 { slave a channel 0 }
            1 { slave a channel 1 }
            2 { slave b channel 0 }
            3 { slave b channel 1 }
        }
    }
    ttable [
        [ 1 0 1 0 ]   # left  -> a.left,  b.left
        [ 0 1 0 1 ]   # right -> a.right, b.right
    ]
}

pcm.loopout {
    type dmix
	ipc_key 1025
	slave.pcm "hw:0,0"
    slave {
        period_time 0
        period_size 1024
        buffer_size 8192
        channels 2
    }
    bindings {
        0 0
        1 1
    }
}

pcm.loopin {
    type plug
	slave.pcm "hw:0,1"
}

pcm.output {
	type dmix
	ipc_key 1024
	slave.pcm "hw:1,0"
    slave {
        period_time 0
        period_size 1024
        buffer_size 8192
        channels 2
    }
    bindings {
        0 0
        1 1
    }
}

**Comment by betojsp** [comment]
**Hardware**

(0, 'Loopback: PCM (hw:0,0)', 32)
(1, 'Loopback: PCM (hw:0,1)', 32)
(2, 'bcm2835 ALSA: - (hw:1,0)', 0)
(3, 'bcm2835 ALSA: IEC958/HDMI (hw:1,1)', 0)

**Comment by maximtrp** [comment]
@betojsp What PCM device is specified in your audio player settings?

**Comment by betojsp** [comment]
@maximtrp everything works well, integrate it with mpd. Thank you https://twitter.com/betojsp/status/1072117207092682753

**Comment by maximtrp** [comment]
@betojsp
Wow, that looks awesome! Thank you for sharing
