### ISSUE TITLE
Pulseaudio

### ISSUE THREAD

**Issue by atchoo78** [maximtrp/spectrumLED#4]
Hi,

Thank you for this. If PulseAudio is installed, there's no need to setup a loopback device, as Pulseaudio provides monitor buses for all audio channels.

Just

```bash

sudo apt-get install pulseaudio

```
and

```bash

python3 spectrumLED.py

```

and it should work instantly.

**Comment by maximtrp** [comment]
Thank you! I haven't tested it with Pulseaudio
